In [1]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns 

pd.set_option("display.max_columns",None)

In [2]:
df = pd.read_csv("../data/telco.csv")

In [3]:
df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,City,Zip Code,Latitude,Longitude,Population,Quarter,Referred a Friend,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,Internet Service,Internet Type,Avg Monthly GB Download,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,Los Angeles,90022,34.023810,-118.156582,68701,Q3,No,0,1,NaN,No,0.00,No,Yes,DSL,8,No,No,Yes,No,No,Yes,No,No,Month-to-Month,Yes,Bank Withdrawal,39.65,39.65,0.00,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,Los Angeles,90063,34.044271,-118.185237,55668,Q3,Yes,1,8,Offer E,Yes,48.85,Yes,Yes,Fiber Optic,17,No,Yes,No,No,No,No,No,Yes,Month-to-Month,Yes,Credit Card,80.65,633.30,0.00,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,Los Angeles,90065,34.108833,-118.229715,47534,Q3,No,0,18,Offer D,Yes,11.33,Yes,Yes,Fiber Optic,52,No,No,No,No,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,Inglewood,90303,33.936291,-118.332639,27778,Q3,Yes,1,25,Offer C,Yes,19.76,No,Yes,Fiber Optic,12,No,Yes,Yes,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,Whittier,90602,33.972119,-118.020188,26265,Q3,Yes,1,37,Offer C,Yes,6.33,Yes,Yes,Fiber Optic,14,No,No,No,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

In [4]:
df.shape

(7043, 50)

In [5]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Under 30', 'Senior Citizen', 'Married',
       'Dependents', 'Number of Dependents', 'Country', 'State', 'City',
       'Zip Code', 'Latitude', 'Longitude', 'Population', 'Quarter',
       'Referred a Friend', 'Number of Referrals', 'Tenure in Months', 'Offer',
       'Phone Service', 'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Satisfaction Score', 'Customer Status', 'Churn Label',
       'Churn Score', 'CLTV', 'Churn Category', 'Churn Reason'],
      dtype='str')

In [6]:
df.info

<bound method DataFrame.info of      Customer ID  Gender  Age Under 30 Senior Citizen Married Dependents  \
0     8779-QRDMV    Male   78       No            Yes      No         No
1     7495-OOKFY  Female   74       No            Yes     Yes        Yes
2     1658-BYGOY    Male   71       No            Yes      No        Yes
3     4598-XLKNJ  Female   78       No            Yes     Yes        Yes
4     4846-WHAFZ  Female   80       No            Yes     Yes        Yes
...          ...     ...  ...      ...            ...     ...        ...
7038  2569-WGERO  Female   30       No             No      No         No
7039  6840-RESVB    Male   38       No             No     Yes        Yes
7040  2234-XADUH  Female   30       No             No     Yes        Yes
7041  4801-JZAZL  Female   32       No             No     Yes        Yes
7042  3186-AJIEK    Male   44       No             No      No         No

      Number of Dependents        Country       State          City  Zip Code  \
0                        0  United States  California   Los Angeles     90022
1                        1  United States  California   Los Angeles     90063
2                        3  United States  California   Los Angeles     90065
3                        1  United States  California     Inglewood     90303
4                        1  United States  California      Whittier     90602
...                    ...            ...         ...           ...       ...
7038                     0  United States  California       Landers     92285
7039                     2  United States  California      Adelanto     92301
7040                     2  United States  California         Amboy     92304
7041                     2  United States  California  Angelus Oaks     92305
7042                     0  United States  California  Apple Valley     92308

       Latitude   Longitude  Population Quarter Referred a Friend  \
0     34.023810 -118.156582       68701      Q3                No
1     34.044271 -118.185237       55668      Q3               Yes
2     34.108833 -118.229715       47534      Q3                No
3     33.936291 -118.332639       27778      Q3               Yes
4     33.972119 -118.020188       26265      Q3               Yes
...         ...         ...         ...     ...               ...
7038  34.341737 -116.539416        2182      Q3                No
7039  34.667815 -117.536183       18980      Q3               Yes
7040  34.559882 -115.637164          42      Q3               Yes
7041  34.167800 -116.864330         301      Q3               Yes
7042  34.424926 -117.184503       28819      Q3                No

      Number of Referrals  Tenure in Months    Offer Phone Service  \
0                       0                 1      NaN            No
1                       1                 8  Offer E           Yes
2                       0                18  Offer D           Yes
3                       1                25  Offer C           Yes
4                       1                37  Offer C           Yes
...                   ...               ...      ...           ...
7038                    0                72      NaN           Yes
7039                    1                24  Offer C           Yes
7040                    4                72      NaN           Yes
7041                    1                11      NaN            No
7042                    0                66      NaN           Yes

      Avg Monthly Long Distance Charges Multiple Lines Internet Service  \
0                                  0.00             No              Yes
1                                 48.85            Yes              Yes
2                                 11.33            Yes              Yes
3                                 19.76             No              Yes
4                                  6.33            Yes              Yes
...                                 ...            ...              ...
7038                              22.77             No               No
7039                              36.05            Yes              Yes
7040                              29.66            Yes              Yes
7041                               0.00             No              Yes
7042                              30.96             No              Yes

     Internet Type  Avg Monthly GB Download Online Security Online Backup  \
0              DSL                        8              No            No
1      Fiber Optic                       17              No           Yes
2      Fiber Optic                       52              No            No
3      Fiber Optic                       12              No           Yes
4      Fiber Optic                       14              No            No
...            ...                      ...             ...           ...
7038           NaN                        0              No            No
7039         Cable                       24             Yes            No
7040   Fiber Optic                       59              No           Yes
7041           DSL                       17             Yes            No
7042   Fiber Optic                       11             Yes            No

     Device Protection Plan Premium Tech Support Streaming TV  \
0                       Yes                   No           No
1                        No                   No           No
2                        No                   No          Yes
3                       Yes                   No          Yes
4                        No                   No           No
...                     ...                  ...          ...
7038                     No                   No           No
7039                    Yes                  Yes          Yes
7040                    Yes                   No          Yes
7041                     No                   No           No
7042                    Yes                  Yes          Yes

     Streaming Movies Streaming Music Unlimited Data        Contract  \
0                 Yes              No             No  Month-to-Month
1                  No              No            Yes  Month-to-Month
2                 Yes             Yes            Yes  Month-to-Month
3                 Yes              No            Yes  Month-to-Month
4                  No              No            Yes  Month-to-Month
...               ...             ...            ...             ...
7038               No              No             No        Two Year
7039              Yes             Yes            Yes        One Year
7040              Yes             Yes            Yes        One Year
7041               No              No            Yes  Month-to-Month
7042              Yes             Yes            Yes        Two Year

     Paperless Billing   Payment Method  Monthly Charge  Total Charges  \
0                  Yes  Bank Withdrawal           39.65          39.65
1                  Yes      Credit Card           80.65         633.30
2                  Yes  Bank Withdrawal           95.45        1752.55
3                  Yes  Bank Withdrawal           98.50        2514.50
4                  Yes  Bank Withdrawal           76.50        2868.15
...                ...              ...             ...            ...
7038               Yes  Bank Withdrawal           21.15        1419.40
7039               Yes     Mailed Check           84.80        1990.50
7040               Yes      Credit Card          103.20        7362.90
7041               Yes  Bank Withdrawal           29.60         346.45
7042               Yes  Bank Withdrawal          105.65        6844.50

      Total Refunds  Total Extra Data Charges  Total Long Distance Charges  \
0              0.00                        20                         0.00
1              0.00                         0                       390.80
2             45.61                         0                       203.94
3             13.43                         0                       494.00
4              0.00                         0                       234.21
...             ...                       ...                          ...
7038          19.31                         0                      1639.44
7039          48.23                         0                       865.20
7040          45.38                         0                      2135.52
7041          27.24                         0                         0.00
7042           0.00                         0                      2043.36

      Total Revenue  Satisfaction Score Customer Status Churn Label  \
0             59.65                   3         Churned         Yes
1           1024.10                   3         Churned         Yes
2           1910.88                   2         Churned         Yes
3           2995.07                   2         Churned         Yes
4           3102.36                   2         Churned         Yes
...             ...                 ...             ...         ...
7038        3039.53                   5          Stayed          No
7039        2807.47                   3          Stayed          No
7040        9453.04                   4          Stayed          No
7041         319.21                   4          Stayed          No
7042        8887.86                   4          Stayed          No

      Churn Score  CLTV   Churn Category                  Churn Reason
0              91  5433       Competitor  Competitor offered more data
1              69  5302       Competitor  Competitor made better offer
2              81  3179       Competitor  Competitor made better offer
3              88  5337  Dissatisfaction     Limited range of services
4              67  2793            Price            Extra data charges
...           ...   ...              ...                           ...
7038           45  5306              NaN                           NaN
7039           59  2140              NaN                           NaN
7040           71  5560              NaN                           NaN
7041           59  2793              NaN                           NaN
7042           38  5097              NaN                           NaN

[7043 rows x 50 columns]>

In [7]:
df.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Churn Score,CLTV
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,22139.603294,1.951867,32.386767,22.958954,20.515405,64.761692,2280.381264,1.962182,6.860713,749.099262,3034.379056,3.244924,58.505040,4400.295755
std,16.750352,0.962802,1856.767505,2.468929,2.154425,21152.392837,3.001199,24.542061,15.448113,20.418940,30.090047,2266.220462,7.902614,25.104978,846.660055,2865.204542,1.201657,21.170031,1183.057152
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,11.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.800000,0.000000,0.000000,0.000000,21.360000,1.000000,5.000000,2003.000000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,2344.000000,0.000000,9.000000,9.210000,3.000000,35.500000,400.150000,0.000000,0.000000,70.545000,605.610000,3.000000,40.000000,3469.000000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,17554.000000,0.000000,29.000000,22.890000,17.000000,70.350000,1394.550000,0.000000,0.000000,401.440000,2108.640000,3.000000,61.000000,4527.000000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,36125.000000,3.000000,55.000000,36.395000,27.000000,89.850000,3786.600000,0.000000,0.000000,1191.100000,4801.145000,4.000000,75.500000,5380.500000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,105285.000000,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000,5.000000,96.000000,6500.000000

In [8]:
df.describe(include="object")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_31908\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Customer ID,Gender,Under 30,Senior Citizen,Married,Dependents,Country,State,City,Quarter,Referred a Friend,Offer,Phone Service,Multiple Lines,Internet Service,Internet Type,Online Security,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Customer Status,Churn Label,Churn Category,Churn Reason
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,3166,7043,7043,7043,5517,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,1869,1869
unique,7043,2,2,2,2,2,1,1,1106,1,2,5,2,2,2,3,2,2,2,2,2,2,2,2,3,2,3,3,2,5,20
top,8779-QRDMV,Male,No,No,No,No,United States,California,Los Angeles,Q3,No,Offer B,Yes,No,Yes,Fiber Optic,No,No,No,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,Stayed,No,Competitor,Competitor had better devices
freq,1,3555,5642,5901,3641,5416,7043,7043,293,7043,3821,824,6361,4072,5517,3035,5024,4614,4621,4999,4336,4311,4555,4745,3610,4171,3909,4720,5174,841,313

In [9]:
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)